# Generated by Django 5.0.7 on 2024-08-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='bio',
            field=models.TextField(blank=True, default='no bio', max_length=500),
        ),
    ]
